# config.yaml
motion_planning:
  initial_nodes: 100
  initial_step_size: 8.0

pce_planner:
  num_samples: 500     # Number of Monte Carlo samples
  num_iterations: 1000   # Number of optimization iterations
  temperature: 1.0     # Gamma parameter
  convergence_threshold: 0.001 # Cost value to stop optimization at
  
  cost:
    epsilon_sdf: 5.0  # Hinge loss cut-off distance
    sigma_obs: 1.5     # Weight for obstacle violations