# config.yaml
motion_planning:
  initial_nodes: 5000
  initial_step_size: 8.0
  node_collision_radius: 5.0 

pce_planner:
  num_samples: 500
  num_iterations: 1000
  temperature: 5.0
  convergence_threshold: 0.5
  
  cost:
    epsilon_sdf: 5.0
    sigma_obs: 1.0