motion_planning:
  initial_nodes: 500
  initial_step_size: 50.0
  node_collision_radius: 10.0 # This replaces TRAJECTORY_RADIUS

pce_planner:
  num_samples: 2000
  num_iterations: 500
  eta:  10
  temperature: 100
  convergence_threshold: 0.1

cost:
  epsilon_sdf: 5.0
  sigma_obs: 0.01

ngd_planner:
  num_samples: 2000
  num_iterations: 500
  learning_rate:  0.99
  convergence_threshold: 0.1

cost:
  epsilon_sdf: 5.0
  sigma_obs: 0.01