# config.yaml
motion_planning:
  num_discretization: 500
  total_time: 50.0
  node_collision_radius: 15.0 

pce_planner:
  num_samples: 3000
  num_iterations: 100
  eta:  10
  temperature: 0.99
  convergence_threshold: 0.01
  
  cost:
    epsilon_sdf: 5.0
    sigma_obs: 0.01

ngd_planner:
  num_samples: 3000
  num_iterations: 100
  learning_rate:  0.99
  convergence_threshold: 0.01
  
  cost:
    epsilon_sdf: 5.0
    sigma_obs: 0.01